version: '3'
services:
  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    image: postgres:latest
    privileged: true
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  flask:
    container_name: flask
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./flask/src:/app
    environment:
      - FLASK_APP=./flask/src/app.py
      - FLASK_RUN_HOST=0.0.0.0
      - PYTHONPATH=/app

  redis:
    image: "redis:alpine"

  nodejs:
    container_name: nodeJS
    build:
      context: ./nodeJS
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres