version: '3'
services:
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./flask/src:/app
    environment:
      - FLASK_APP=./flask/src/app.py
      - FLASK_RUN_HOST=0.0.0.0
      - PYTHONPATH=/app
  redis:
    image: "redis:alpine"